version: "3.9" ## especifica a versão do docker-compose file

services: ## Define um serviço
  app: ## nome do serviço
    build: . ## localização do dockerfile
    command: npm start ## comando a executar
    ports:
      - "4000:4000" ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
    volumes:
      - .:/usr/app ## monitoro a pasta atual . e envio as alterações para /usr/app
    env_file: ./.env
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$DB_NAME
    depends_on:
      - mongodb
    networks:
      - graphql-study

  mongodb:
    image: mongo
    restart: 'no'
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 27017:27017
    networks:
      - graphql-study
    volumes:
      - db:/data/db
    stdin_open: true
    tty: true


volumes:
  db:

networks:
  graphql-study:
    driver: bridge
    